"""make entity_merge_log fk columns nullable

Revision ID: d54b602e9f93
Revises: 8eac469c307e
Create Date: 2026-06-16 14:27:22.362842

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54b602e9f93'
down_revision: str | Sequence[str] | None = '8eac469c307e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_merge_log', 'merged_from_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('entity_merge_log', 'merged_into_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entity_merge_log', 'merged_into_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('entity_merge_log', 'merged_from_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
