"""change entity_merge_log fk to set null

Revision ID: 8eac469c307e
Revises: 38be8f099d90
Create Date: 2026-06-16 14:27:06.457247

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8eac469c307e'
down_revision: str | Sequence[str] | None = '38be8f099d90'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entity_merge_log_merged_from_id_fkey'), 'entity_merge_log', type_='foreignkey')
    op.drop_constraint(op.f('entity_merge_log_merged_into_id_fkey'), 'entity_merge_log', type_='foreignkey')
    op.create_foreign_key(op.f('entity_merge_log_merged_into_id_fkey'), 'entity_merge_log', 'entities', ['merged_into_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('entity_merge_log_merged_from_id_fkey'), 'entity_merge_log', 'entities', ['merged_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entity_merge_log_merged_into_id_fkey'), 'entity_merge_log', type_='foreignkey')
    op.drop_constraint(op.f('entity_merge_log_merged_from_id_fkey'), 'entity_merge_log', type_='foreignkey')
    op.create_foreign_key(op.f('entity_merge_log_merged_into_id_fkey'), 'entity_merge_log', 'entities', ['merged_into_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('entity_merge_log_merged_from_id_fkey'), 'entity_merge_log', 'entities', ['merged_from_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
