"""add source_plan column and query_plans table

Revision ID: 4bd96e67635d
Revises: f4859fa28eea
Create Date: 2026-06-24 03:34:50.425881

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd96e67635d'
down_revision: str | Sequence[str] | None = 'f4859fa28eea'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('raw_query', sa.Text(), nullable=False),
    sa.Column('classified_type', sa.Text(), nullable=False),
    sa.Column('retrieval_depth', sa.Text(), nullable=False),
    sa.Column('seed_count', sa.Integer(), nullable=False),
    sa.Column('termination_condition', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('classification_source', sa.Text(), nullable=False),
    sa.Column('model_used', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('planner_version', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ttl_days', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sources', sa.Column('source_plan', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'source_plan')
    op.drop_table('query_plans')
    # ### end Alembic commands ###
