"""add confidence_tag and confidence_score to relations

Revision ID: f4859fa28eea
Revises: 4b237e08e0bd
Create Date: 2026-06-18 04:02:15.885517

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f4859fa28eea"
down_revision: str | Sequence[str] | None = "4b237e08e0bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("relations", sa.Column("confidence_tag", sa.Text(), server_default="INFERRED", nullable=False))
    op.add_column("relations", sa.Column("confidence_score", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("relations", "confidence_score")
    op.drop_column("relations", "confidence_tag")
    # ### end Alembic commands ###
