"""drop entity_merge_log foreign key constraints

Revision ID: 9c29d1174c14
Revises: 8b7890b0eb7a
Create Date: 2026-06-16 08:51:06.472478

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c29d1174c14'
down_revision: str | Sequence[str] | None = '8b7890b0eb7a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('entity_merge_log_merged_from_id_fkey'), 'entity_merge_log', type_='foreignkey')
    op.drop_constraint(op.f('entity_merge_log_merged_into_id_fkey'), 'entity_merge_log', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('entity_merge_log_merged_into_id_fkey'), 'entity_merge_log', 'entities', ['merged_into_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('entity_merge_log_merged_from_id_fkey'), 'entity_merge_log', 'entities', ['merged_from_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
