"""add entity_merge_log table

Revision ID: 38be8f099d90
Revises: 12caf0657a27
Create Date: 2026-06-16 06:03:28.367725

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38be8f099d90'
down_revision: str | Sequence[str] | None = '12caf0657a27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_merge_log',
    sa.Column('merged_from_id', sa.UUID(), nullable=False),
    sa.Column('merged_into_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merged_from_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merged_into_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_entity_merge_log_merged_from_id', 'entity_merge_log', ['merged_from_id'], unique=False)
    op.create_index('idx_entity_merge_log_merged_into_id', 'entity_merge_log', ['merged_into_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_entity_merge_log_merged_into_id', table_name='entity_merge_log')
    op.drop_index('idx_entity_merge_log_merged_from_id', table_name='entity_merge_log')
    op.drop_table('entity_merge_log')
    # ### end Alembic commands ###
