"""add completed_at to jobs

Revision ID: 8b7890b0eb7a
Revises: d54b602e9f93
Create Date: 2026-06-16 08:16:53.003402

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b7890b0eb7a'
down_revision: str | Sequence[str] | None = 'd54b602e9f93'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'completed_at')
    # ### end Alembic commands ###
