"""add wiki synthesis columns and job target_entity_id

Revision ID: 4b237e08e0bd
Revises: 9c29d1174c14
Create Date: 2026-06-17 06:26:58.820676

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b237e08e0bd'
down_revision: str | Sequence[str] | None = '9c29d1174c14'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('target_entity_id', sa.UUID(), nullable=True))
    op.create_index('idx_jobs_target_entity_id', 'jobs', ['target_entity_id'], unique=False)
    op.add_column('wiki_pages', sa.Column('synthesized_from_sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('wiki_pages', sa.Column('synthesized_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki_pages', 'synthesized_at')
    op.drop_column('wiki_pages', 'synthesized_from_sources')
    op.drop_index('idx_jobs_target_entity_id', table_name='jobs')
    op.drop_column('jobs', 'target_entity_id')
    # ### end Alembic commands ###
